collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4462366
color:
  saturation: 0.970176
  lightness: 0.4995951
  brandStrength: 0.3036075
  brandColors:
    - '#999792'
    - '#1B120B'
    - '#DFF0FA'
    - '#454138'
    - '#911F20'
  rhythmicContrast: 0.2131068
layout_spectrum: 1
name: ryanojohn
