layout_spectrum: 1
typography_spectrum: 0.4462366
color:
  saturation: 0.970176
  lightness: 0.4995951
  brandStrength: 0.3036075
  rhythmicContrast: 0.2131068
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: ryanojohn
